---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tags:
    Name: ASG-WebApp-Server
  instance-state-name: running

keyed_groups:
  - key: tags.Name
    prefix: ""

compose:
  ansible_host: public_ip_address

##