name: Deploy A[[ to aws

on:
  push:
    branches:
      - Ansi_CI/CD_Terra2LV

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      # Create folder in vm
      - name: Checkout Ansible code
        uses: actions/checkout@v4
        with:
          repository: KurosuSama/vprofile_dockerization
          path: ansible_code

      # Secrets in GitHub
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Setup Python & Ansible
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/aws_key
          chmod 600 ~/.ssh/aws_key
          
      - name: Get Runner IP
        id: get_ip
        run: echo "runner_ip=$(curl -s 'https://api.ipify.org')" >> $GITHUB_OUTPUT
      
      - name: Whitelist Runner IP in Security Group
        run: |
          echo "Adding IP ${{ steps.get_ip.outputs.runner_ip }} to SG ${{ secrets.APP_SG_ID }}"
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.APP_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.get_ip.outputs.runner_ip }}/32

      - name: Check ansible_host
        run: |
          cd ansible_code/ansible        
          ansible-inventory -i aws_ec2.yml --graph

      - name: Run Playbook
        run: |
          cd ansible_code/ansible
          ansible-playbook -i aws_ec2.yml playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      # 8. ВИДАЛЯЄМО IP з Security Group (ЗАВЖДИ)
      - name: Remove Runner IP from Security Group
        # Цей крок виконається ЗАВЖДИ, навіть якщо Ansible впаде
        if: always() 
        run: |
          echo "Removing IP ${{ steps.get_ip.outputs.runner_ip }} from SG ${{ secrets.APP_SG_ID }}"
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.APP_SG_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.get_ip.outputs.runner_ip }}/32
        
